spring:
  # PostgreSQL DB 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

mybatis:
  mapUnderscoreToCamelCase: true
  type-aliases-package: com.example.demo.model
  mapper-locations: mybatis-mapper/*.xml
